"""add purchases tables

Revision ID: 011c4a6b3563
Revises: b44c94b57364
Create Date: 2026-09-11 14:59:09.223208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '011c4a6b3563'
down_revision: Union[str, Sequence[str], None] = 'b44c94b57364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase_histories')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_histories',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('loyalty_points_earned', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('purchased_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint("item_type::text = ANY (ARRAY['drink'::character varying, 'baked_good'::character varying]::text[])", name=op.f('ck_purchase_histories_item_type')),
    sa.CheckConstraint('item_id > 0', name=op.f('ck_purchase_histories_item_id_positive')),
    sa.CheckConstraint('loyalty_points_earned >= 0', name=op.f('ck_purchase_histories_loyalty_points_non_negative')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_purchase_histories_quantity_positive')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('purchase_histories_customer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('purchase_histories_pkey'))
    )
    # ### end Alembic commands ###
