"""Initial migration setup

Revision ID: 08384a884d18
Revises:
Create Date: 2026-08-31 15:10:22.922305

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "08384a884d18"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "baked_goods",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("purchase_cost", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("retail_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "allergens", sa.ARRAY(sa.String()), server_default="{}", nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "customers",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("loyalty_points", sa.Integer(), nullable=False),
        sa.Column("loyalty_expires_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_customers_email"), "customers", ["email"], unique=True)
    op.create_index(op.f("ix_customers_phone"), "customers", ["phone"], unique=True)
    op.create_table(
        "drinks",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("production_cost", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "markup_percentage", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column("sale_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_drinks_name"), "drinks", ["name"], unique=True)
    op.create_table(
        "employees",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("hourly_rate", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("hire_date", sa.Date(), nullable=False),
        sa.Column("term_date", sa.Date(), nullable=True),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "promotions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("promo_code", sa.String(), nullable=False),
        sa.Column(
            "discount_percentage", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("promo_code"),
    )
    op.create_table(
        "vendors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ingredients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("purchasing_cost", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("unit_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("unit_of_measure", sa.String(), nullable=False),
        sa.Column("allergens", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("vendor_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ingredients_id"), "ingredients", ["id"], unique=False)
    op.create_index(
        "uq_ingredient_name_vendor",
        "ingredients",
        ["name", "vendor_id"],
        unique=True,
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.create_table(
        "vendor_contacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("vendor_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "drink_ingredients",
        sa.Column("drink_id", sa.Integer(), nullable=False),
        sa.Column("ingredient_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("unit", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["drink_id"],
            ["drinks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredients.id"],
        ),
        sa.PrimaryKeyConstraint("drink_id", "ingredient_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("drink_ingredients")
    op.drop_table("vendor_contacts")
    op.drop_index(
        "uq_ingredient_name_vendor",
        table_name="ingredients",
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.drop_index(op.f("ix_ingredients_id"), table_name="ingredients")
    op.drop_table("ingredients")
    op.drop_table("vendors")
    op.drop_table("promotions")
    op.drop_table("employees")
    op.drop_index(op.f("ix_drinks_name"), table_name="drinks")
    op.drop_table("drinks")
    op.drop_index(op.f("ix_customers_phone"), table_name="customers")
    op.drop_index(op.f("ix_customers_email"), table_name="customers")
    op.drop_table("customers")
    op.drop_table("baked_goods")
    # ### end Alembic commands ###
