"""Test staging migration automation

Revision ID: 4afbc40c2e2e
Revises: 08384a884d18
Create Date: 2026-09-01 11:29:05.431124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4afbc40c2e2e'
down_revision: Union[str, Sequence[str], None] = '08384a884d18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promotions', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promotions', 'notes')
    # ### end Alembic commands ###
