"""Add loyalty point audits

Revision ID: 775e6fa11fa6
Revises: 08384a884d18
Create Date: 2026-09-08 11:13:13.710134

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "775e6fa11fa6"
down_revision: str | Sequence[str] | None = "08384a884d18"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "loyalty_point_audit",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("points_expired", sa.Integer(), nullable=False),
        sa.Column("expired_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("loyalty_point_audit")
    # ### end Alembic commands ###
