"""Add item_type to purchase_items

Revision ID: 9511d0dd4bf0
Revises: e00843adab64
Create Date: 2026-09-14 10:49:53.612750

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9511d0dd4bf0"
down_revision: str | Sequence[str] | None = "e00843adab64"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("purchase_items", sa.Column("item_type", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("purchase_items", "item_type")
    # ### end Alembic commands ###
