"""Add blacklisted_tokens

Revision ID: e44c8b475e6a
Revises: 6ef4c9130ad1
Create Date: 2026-09-10 14:42:56.529495

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e44c8b475e6a"
down_revision: str | Sequence[str] | None = "6ef4c9130ad1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blacklisted_tokens",
        sa.Column("jti", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("blacklisted_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("jti"),
    )
    op.create_index(
        op.f("ix_blacklisted_tokens_expires_at"),
        "blacklisted_tokens",
        ["expires_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_blacklisted_tokens_expires_at"), table_name="blacklisted_tokens"
    )
    op.drop_table("blacklisted_tokens")
    # ### end Alembic commands ###
