"""Add InventoryTransaction model

Revision ID: fb4972bc9e6a
Revises: aa0923fd09c6
Create Date: 2026-09-14 15:17:37.570373

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fb4972bc9e6a"
down_revision: str | Sequence[str] | None = "aa0923fd09c6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventory_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("baked_good_id", sa.Integer(), nullable=True),
        sa.Column("ingredient_id", sa.Integer(), nullable=True),
        sa.Column("change_type", sa.String(), nullable=False),
        sa.Column("quantity_delta", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("reference_id", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "(baked_good_id IS NOT NULL AND ingredient_id IS NULL) OR "
            "(baked_good_id IS NULL AND ingredient_id IS NOT NULL)",
            name="ck_inventory_transaction_exclusive_item",
        ),
        sa.ForeignKeyConstraint(
            ["baked_good_id"],
            ["baked_goods.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_transactions_baked_good_id"),
        "inventory_transactions",
        ["baked_good_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_transactions_id"),
        "inventory_transactions",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_transactions_ingredient_id"),
        "inventory_transactions",
        ["ingredient_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_inventory_transactions_ingredient_id"),
        table_name="inventory_transactions",
    )
    op.drop_index(
        op.f("ix_inventory_transactions_id"), table_name="inventory_transactions"
    )
    op.drop_index(
        op.f("ix_inventory_transactions_baked_good_id"),
        table_name="inventory_transactions",
    )
    op.drop_table("inventory_transactions")
    # ### end Alembic commands ###
