/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate an employee and return a JWT access token.
         *
         *     Accepts standard OAuth2 form data (username, password).
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Terminate the caller's current session.
         *
         *     Adds the token's jti to the blacklist so it can no longer be used,
         *     even thought it hasn't reached its natural expiry yet.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/baked-goods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Baked Good
         * @description Create a new baked good.
         *
         *     Returns the created baked good, including its generated ID.
         */
        post: operations["create_baked_good_baked_goods_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Customers
         * @description List all customer records in the system.
         */
        get: operations["list_customers_customers_get"];
        put?: never;
        /**
         * Create Customer
         * @description Create a new customer record.
         *
         *     Both email and phone must be unique.
         */
        post: operations["create_customer_customers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Customer
         * @description Retrieve a single customer by ID.
         */
        get: operations["get_customer_customers__id__get"];
        /**
         * Update Customer
         * @description Update an existing customer.
         *
         *     Both email and phone must be unique. Loyalty expiration is not editable
         *     here; it is only ever set on creation.
         */
        put: operations["update_customer_customers__id__put"];
        post?: never;
        /**
         * Delete Customer
         * @description Soft delete a customer.
         *
         *     The customer remains in the database for historical records but is no
         *     longer visible or available for use. Its email and phone number are
         *     cleared to free them up for future customers.
         */
        delete: operations["delete_customer_customers__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drinks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Drink
         * @description Create a new drink recipe.
         */
        post: operations["create_drink_drinks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Employees
         * @description Retrieve a list of all employees.
         *
         *     Returns each employee without the password field.
         */
        get: operations["list_employees_employees_get"];
        put?: never;
        /**
         * Create Employee
         * @description Create a new employee and persist it to the database.
         *
         *     Returns the created employee without the password field.
         */
        post: operations["create_employee_employees_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Employee
         * @description Retrieve a single employee by ID.
         *
         *     Returns the employee without the password field.
         */
        get: operations["get_employee_employees__id__get"];
        /**
         * Update Employee
         * @description Update an existing employee.
         *
         *     Returns the updated employee without the password field.
         *     The employee's password cannot be updated via this endpoint. If a
         *     password is provided in the request body, it will be silently ignored.
         */
        put: operations["update_employee_employees__id__put"];
        post?: never;
        /**
         * Delete Employee
         * @description Soft delete an employee.
         *
         *     The employee remains in the database for historical records
         *     but is no longer active or able to log in. As part of
         *     the successful request, the employee's username is mutated
         *     (e.g., {username}_deleted_{id}) to free it up for future use.
         */
        delete: operations["delete_employee_employees__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Ingredients
         * @description Returns a list of all ingredient records in the system.
         */
        get: operations["list_ingredients_ingredients_get"];
        put?: never;
        /**
         * Create Ingredient
         * @description Create a new ingredient and link it to an existing vendor.
         */
        post: operations["create_ingredient_ingredients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingredients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ingredient
         * @description Retrieve a single ingredient by ID.
         */
        get: operations["get_ingredient_ingredients__id__get"];
        /**
         * Update Ingredient
         * @description Update an existing ingredient.
         */
        put: operations["update_ingredient_ingredients__id__put"];
        post?: never;
        /**
         * Delete Ingredient
         * @description Delete an existing ingredient (soft delete).
         */
        delete: operations["delete_ingredient_ingredients__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/promotions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Promotions
         * @description Return all non-deleted Promotions.
         *
         *     Returns all Promotions currently stored in the system
         *     that have not been soft deleted.
         */
        get: operations["list_promotions_promotions_get"];
        put?: never;
        /**
         * Create Promotion
         * @description Create a new promotion.
         *
         *     Returns the created promotion with its generated ID.
         */
        post: operations["create_promotion_promotions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/promotions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Promotion
         * @description Retrieve a single promotion by ID.
         *
         *     Returns the requested promotion.
         */
        get: operations["get_promotion_promotions__id__get"];
        /**
         * Update Promotion
         * @description Update a promotion.
         *
         *     Returns the updated promotion.
         */
        put: operations["update_promotion_promotions__id__put"];
        post?: never;
        /**
         * Delete Promotion
         * @description Soft delete a Promotion.
         *
         *     The Promotion remains in the database for historical records
         *     but is no longer visible or available for use.
         */
        delete: operations["delete_promotion_promotions__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Vendors
         * @description Retrieve a list of all vendors.
         */
        get: operations["list_vendors_vendors_get"];
        put?: never;
        /**
         * Create Vendor
         * @description Create a new vendor, along with its initial set of contacts.
         *
         *     Returns the created vendor, including generated IDs for the vendor
         *     and each vendor contact.
         */
        post: operations["create_vendor_vendors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Vendor
         * @description Update an existing vendor and its contacts.
         *
         *     The list of contacts is processed in the following way:
         *     - If the contact has an ID, the existing contact with that ID will be updated.
         *     - If the contact does not have an ID, a new contact will be created.
         *     - Any of the vendor's existing contacts without a corresponding contact in
         *       the request will be deleted.
         */
        put: operations["update_vendor_vendors__id__put"];
        post?: never;
        /**
         * Delete Vendor
         * @description Delete the vendor and its associated contacts.
         */
        delete: operations["delete_vendor_vendors__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/purchases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Purchase
         * @description Process a new purchase.
         *
         *     Looks up item prices, applies promotions, calculates taxes, and updates
         *     customer loyalty points.
         */
        post: operations["create_purchase_purchases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Check the health of the API.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Check the health of the database.
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BakedGoodCreate
         * @description Represents a baked good before it has been saved to the database.
         */
        BakedGoodCreate: {
            /**
             * Active
             * @description Whether or not the baked good is active
             * @default true
             */
            active: boolean;
            /**
             * Name
             * @description The name of the baked good
             */
            name: string;
            /**
             * Description
             * @description A description of the baked good
             */
            description: string;
            /**
             * Purchase Cost
             * @description The purchase cost, in dollars per baked good
             */
            purchase_cost: number | string;
            /**
             * Retail Price
             * @description The retail price, in dollars per baked good
             */
            retail_price: number | string;
            /**
             * Allergens
             * @description A list of any allergens present in the baked good
             */
            allergens: string[];
        };
        /**
         * BakedGoodRead
         * @description The baked good representation returned to an API client.
         */
        BakedGoodRead: {
            /**
             * Active
             * @description Whether or not the baked good is active
             * @default true
             */
            active: boolean;
            /**
             * Name
             * @description The name of the baked good
             */
            name: string;
            /**
             * Description
             * @description A description of the baked good
             */
            description: string;
            /**
             * Purchase Cost
             * @description The purchase cost, in dollars per baked good
             */
            purchase_cost: string;
            /**
             * Retail Price
             * @description The retail price, in dollars per baked good
             */
            retail_price: string;
            /**
             * Allergens
             * @description A list of any allergens present in the baked good
             */
            allergens: string[];
            /**
             * ID
             * @description The unique identifier for this baked good
             */
            id: number;
        };
        /** Body_login_auth_login_post */
        Body_login_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /**
         * CustomerCreate
         * @description Payload for creating a new customer.
         *
         *     At least email or phone must be provided.
         */
        CustomerCreate: {
            /**
             * Activity Status
             * @description The activity status of the customer
             * @default true
             */
            active: boolean;
            /**
             * First Name
             * @description The first name of the customer
             */
            first_name: string;
            /**
             * Last Name
             * @description The last name of the customer
             */
            last_name: string;
            /**
             * Email
             * @description The unique email of the customer
             */
            email?: string | null;
            /**
             * Phone Number
             * @description The unique phone number of the customer
             */
            phone?: string | null;
            /**
             * Loyalty Points
             * @description The amount of loyalty points the customer has
             * @default 0
             */
            loyalty_points: number;
            /**
             * Loyalty Points Expiration Date
             * Format: date-time
             * @description The loyalty points expires one year after creation
             */
            loyalty_expires_at?: string;
        };
        /**
         * CustomerRead
         * @description Customer schema returned from the system.
         */
        CustomerRead: {
            /**
             * Activity Status
             * @description The activity status of the customer
             * @default true
             */
            active: boolean;
            /**
             * First Name
             * @description The first name of the customer
             */
            first_name: string;
            /**
             * Last Name
             * @description The last name of the customer
             */
            last_name: string;
            /**
             * Email
             * @description The unique email of the customer
             */
            email?: string | null;
            /**
             * Phone Number
             * @description The unique phone number of the customer
             */
            phone?: string | null;
            /**
             * Loyalty Points
             * @description The amount of loyalty points the customer has
             * @default 0
             */
            loyalty_points: number;
            /**
             * Customer ID
             * @description The generated ID of the customer
             */
            id: number;
            /**
             * Loyalty Points Expiration Date
             * Format: date-time
             * @description The loyalty points expires one year after creation
             */
            loyalty_expires_at: string;
        };
        /**
         * CustomerUpdate
         * @description Payload for updating an existing customer.
         *
         *     Loyalty expiration is not editable here; it is only ever set on creation.
         */
        CustomerUpdate: {
            /**
             * Activity Status
             * @description The activity status of the customer
             * @default true
             */
            active: boolean;
            /**
             * First Name
             * @description The first name of the customer
             */
            first_name: string;
            /**
             * Last Name
             * @description The last name of the customer
             */
            last_name: string;
            /**
             * Email
             * @description The unique email of the customer
             */
            email?: string | null;
            /**
             * Phone Number
             * @description The unique phone number of the customer
             */
            phone?: string | null;
            /**
             * Loyalty Points
             * @description The amount of loyalty points the customer has
             * @default 0
             */
            loyalty_points: number;
        };
        /**
         * DrinkCreate
         * @description Input schema for creating a new drink recipe.
         */
        DrinkCreate: {
            /**
             * Drink Activity Status
             * @description The activity status of the drink
             * @default true
             */
            active: boolean;
            /**
             * Drink Name
             * @description The drink recipe name
             */
            name: string;
            /**
             * Drink Description
             * @description The drink's description
             */
            description: string;
            /**
             * Drink Type
             * @description The type of drink and must be one: coffee, tea, soda, refresher, other
             */
            type: string;
            /**
             * Markup Percentage
             * @description The drink's markup percentage
             */
            markup_percentage: number | string;
            /**
             * Drink Ingredients
             * @description The ingredients required for the drink recipe
             */
            ingredients: components["schemas"]["DrinkIngredientCreateNested"][];
        };
        /**
         * DrinkIngredientCreateNested
         * @description Input schema for attaching an existing ingredient to a new drink recipe.
         */
        DrinkIngredientCreateNested: {
            /**
             * Ingredient ID
             * @description The unique identifier of the ingredient
             */
            ingredient_id: number;
            /**
             * Ingredient Amount
             * @description The ingredient required for the drink recipe
             */
            amount: number | string;
            /**
             * Ingredient Unit
             * @description The ingredient's unit of measurement
             */
            unit: string;
        };
        /**
         * DrinkIngredientRead
         * @description Represents an ingredient for a unique drink recipe in the system.
         */
        DrinkIngredientRead: {
            /**
             * Ingredient ID
             * @description The unique identifier of the ingredient
             */
            ingredient_id: number;
            /**
             * Ingredient Amount
             * @description The ingredient required for the drink recipe
             */
            amount: string;
            /**
             * Ingredient Unit
             * @description The ingredient's unit of measurement
             */
            unit: string;
        };
        /**
         * DrinkRead
         * @description Represents a new drink recipe in the system.
         */
        DrinkRead: {
            /**
             * Drink Activity Status
             * @description The activity status of the drink
             * @default true
             */
            active: boolean;
            /**
             * Drink Name
             * @description The drink recipe name
             */
            name: string;
            /**
             * Drink Description
             * @description The drink's description
             */
            description: string;
            /**
             * Drink Type
             * @description The type of drink and must be one: coffee, tea, soda, refresher, other
             */
            type: string;
            /**
             * Markup Percentage
             * @description The drink's markup percentage
             */
            markup_percentage: string;
            /**
             * Drink ID
             * @description The unique identifier of the drink
             */
            id: number;
            /**
             * Drink Ingredients
             * @description The ingredients required for the drink recipe
             */
            ingredients: components["schemas"]["DrinkIngredientRead"][];
            /**
             * Drink Production Cost
             * @description The purchasing cost sum of all ingredients required for the drink
             */
            production_cost: string;
            /**
             * Drink Sale Price
             * @description The product of the drink's markup percentage and production cost
             */
            sale_price: string;
        };
        /**
         * EmployeeCreate
         * @description Payload for creating a new employee.
         */
        EmployeeCreate: {
            /**
             * Active
             * @description Whether the employee is currently active
             * @default true
             */
            active: boolean;
            /**
             * First Name
             * @description The employee's first name
             */
            first_name: string;
            /**
             * Last Name
             * @description The employee's last name
             */
            last_name: string;
            /**
             * Role
             * @description The employee's role in the company
             */
            role: components["schemas"]["EmployeeRole"];
            /**
             * Hourly Rate
             * @description The employee's hourly rate in dollars. Must be greater than 0, with at most 10 digits and 2 decimal places.
             */
            hourly_rate: number | string;
            /**
             * Hire Date
             * Format: date
             * @description The date the employee was hired
             */
            hire_date: string;
            /**
             * Termination Date
             * @description The date the employee was terminated, if applicable. Must be later than hire_date.
             */
            term_date?: string | null;
            /**
             * Username
             * @description The employee's username for system access
             */
            username: string;
            /**
             * Password
             * @description The employee's password for system access. Must be at least 8 characters and include a capital letter, a number, and a special character. Allowed special characters: !@#$%^&*()_+-=[]{};':"\|,.<>/?`~
             */
            password: string;
        };
        /**
         * EmployeeRead
         * @description Employee schema returned from the system.
         */
        EmployeeRead: {
            /**
             * Active
             * @description Whether the employee is currently active
             */
            active: boolean;
            /**
             * First Name
             * @description The employee's first name
             */
            first_name: string;
            /**
             * Last Name
             * @description The employee's last name
             */
            last_name: string;
            /**
             * Role
             * @description The employee's role in the company
             */
            role: components["schemas"]["EmployeeRole"];
            /**
             * Hourly Rate
             * @description The employee's hourly rate in dollars. Must be greater than 0, with at most 10 digits and 2 decimal places.
             */
            hourly_rate: string;
            /**
             * Hire Date
             * Format: date
             * @description The date the employee was hired
             */
            hire_date: string;
            /**
             * Termination Date
             * @description The date the employee was terminated, if applicable. Must be later than hire_date.
             */
            term_date?: string | null;
            /**
             * Username
             * @description The employee's username for system access
             */
            username: string;
            /**
             * Employee ID
             * @description The unique identifier of the employee
             */
            id: number;
        };
        /**
         * EmployeeRole
         * @description Allowed employee roles.
         * @enum {string}
         */
        EmployeeRole: "employee" | "manager" | "admin";
        /**
         * EmployeeUpdate
         * @description Payload for updating an existing employee's profile.
         */
        EmployeeUpdate: {
            /**
             * Active
             * @description Whether the employee is currently active
             */
            active: boolean;
            /**
             * First Name
             * @description The employee's first name
             */
            first_name: string;
            /**
             * Last Name
             * @description The employee's last name
             */
            last_name: string;
            /**
             * Role
             * @description The employee's role in the company
             */
            role: components["schemas"]["EmployeeRole"];
            /**
             * Hourly Rate
             * @description The employee's hourly rate in dollars. Must be greater than 0, with at most 10 digits and 2 decimal places.
             */
            hourly_rate: number | string;
            /**
             * Hire Date
             * Format: date
             * @description The date the employee was hired
             */
            hire_date: string;
            /**
             * Termination Date
             * @description The date the employee was terminated, if applicable. Must be later than hire_date.
             */
            term_date?: string | null;
            /**
             * Username
             * @description The employee's username for system access
             */
            username: string;
        };
        /**
         * IngredientCreate
         * @description Represents an ingredient before it has been saved to the database.
         */
        IngredientCreate: {
            /**
             * Name
             * @description The name of the ingredient
             */
            name: string;
            /**
             * Purchasing Cost
             * @description The cost to purchase the ingredient
             */
            purchasing_cost: number | string;
            /**
             * Unit Amount
             * @description The amount per unit of measure
             */
            unit_amount: number | string;
            /**
             * Unit of Measure
             * @description The unit used to measure this ingredient
             */
            unit_of_measure: string;
            /**
             * Vendor ID
             * @description The ID of the vendor supplying this ingredient
             */
            vendor_id: number;
            /**
             * Active
             * @description Whether or not the ingredient is active
             * @default true
             */
            active: boolean;
            /**
             * Allergens
             * @description A list of allergens present in the ingredient
             */
            allergens?: string[];
        };
        /**
         * IngredientRead
         * @description The ingredient representation returned to an API client.
         */
        IngredientRead: {
            /**
             * Name
             * @description The name of the ingredient
             */
            name: string;
            /**
             * Purchasing Cost
             * @description The cost to purchase the ingredient
             */
            purchasing_cost: string;
            /**
             * Unit Amount
             * @description The amount per unit of measure
             */
            unit_amount: string;
            /**
             * Unit of Measure
             * @description The unit used to measure this ingredient
             */
            unit_of_measure: string;
            /**
             * Vendor ID
             * @description The ID of the vendor supplying this ingredient
             */
            vendor_id: number;
            /**
             * Active
             * @description Whether or not the ingredient is active
             * @default true
             */
            active: boolean;
            /**
             * Allergens
             * @description A list of allergens present in the ingredient
             */
            allergens?: string[];
            /**
             * Ingredient ID
             * @description The unique identifier for this ingredient
             */
            id: number;
        };
        /**
         * IngredientUpdate
         * @description Input schema for updating an existing ingredient.
         */
        IngredientUpdate: {
            /**
             * Name
             * @description The name of the ingredient
             */
            name: string;
            /**
             * Purchasing Cost
             * @description The cost to purchase the ingredient
             */
            purchasing_cost: number | string;
            /**
             * Unit Amount
             * @description The amount per unit of measure
             */
            unit_amount: number | string;
            /**
             * Unit of Measure
             * @description The unit used to measure this ingredient
             */
            unit_of_measure: string;
            /**
             * Vendor ID
             * @description The ID of the vendor supplying this ingredient
             */
            vendor_id: number;
            /**
             * Active
             * @description Whether or not the ingredient is active
             * @default true
             */
            active: boolean;
            /**
             * Allergens
             * @description A list of allergens present in the ingredient
             */
            allergens?: string[];
        };
        /**
         * PromotionCreate
         * @description Request model used when creating a new promotion.
         */
        PromotionCreate: {
            /** Active */
            active: boolean;
            /** Promo Code */
            promo_code: string;
            /** Discount Percentage */
            discount_percentage: number | string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
        };
        /**
         * PromotionRead
         * @description Response model returned when viewing a promotion.
         */
        PromotionRead: {
            /** Active */
            active: boolean;
            /** Promo Code */
            promo_code: string;
            /** Discount Percentage */
            discount_percentage: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Id */
            id: number;
        };
        /**
         * PromotionUpdate
         * @description Request model used when updating an existing promotion.
         */
        PromotionUpdate: {
            /** Active */
            active: boolean;
            /** Promo Code */
            promo_code: string;
            /** Discount Percentage */
            discount_percentage: number | string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
        };
        /** PurchaseCreate */
        PurchaseCreate: {
            /** Customer Id */
            customer_id?: number | null;
            /** Promo Id */
            promo_id?: number | null;
            /** Items */
            items: components["schemas"]["PurchaseItemCreateNested"][];
        };
        /**
         * PurchaseItemCreateNested
         * @description Input schema for an item nested inside a PurchaseCreate payload.
         */
        PurchaseItemCreateNested: {
            /** Name */
            name: string;
            /**
             * Quantity
             * @default 1
             */
            quantity: number;
        };
        /** PurchaseItemRead */
        PurchaseItemRead: {
            /** Id */
            id: number;
            /** Purchase Id */
            purchase_id: number;
            /** Item Type */
            item_type: string;
            /** Name */
            name: string;
            /** Quantity */
            quantity: number;
            /** Unit Price */
            unit_price: string;
        };
        /** PurchaseRead */
        PurchaseRead: {
            /** Id */
            id: number;
            /** Customer Id */
            customer_id: number | null;
            /** Promo Id */
            promo_id: number | null;
            /** Subtotal */
            subtotal: string;
            /** Tax */
            tax: string;
            /** Total */
            total: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Items */
            items: components["schemas"]["PurchaseItemRead"][];
        };
        /**
         * Token
         * @description Token schema returned from the system.
         */
        Token: {
            /**
             * Access Token
             * @description The JWT access token for the authenticated employee
             */
            access_token: string;
            /**
             * Token Type
             * @description The type of the access token
             */
            token_type: string;
        };
        /**
         * VendorContactCreateNested
         * @description Does not include vendor_id
         */
        VendorContactCreateNested: {
            /**
             * Vendor Contact Name
             * @description The vendor contact's name
             */
            name: string;
            /**
             * Vendor Contact Role
             * @description The vendor contact's role
             */
            role: string;
            /**
             * Vendor Contact Email
             * @description The vendor contact's email
             */
            email: string;
            /**
             * Vendor Contact Phone
             * @description The vendor contact's phone
             */
            phone: string;
        };
        /** VendorContactRead */
        VendorContactRead: {
            /**
             * Vendor Contact Name
             * @description The vendor contact's name
             */
            name: string;
            /**
             * Vendor Contact Role
             * @description The vendor contact's role
             */
            role: string;
            /**
             * Vendor Contact Email
             * @description The vendor contact's email
             */
            email: string;
            /**
             * Vendor Contact Phone
             * @description The vendor contact's phone
             */
            phone: string;
            /**
             * Vendor ID
             * @description The ID of this contact's vendor
             */
            vendor_id: number;
            /**
             * Vendor Contact ID
             * @description The vendor contact ID
             */
            id: number;
        };
        /** VendorContactUpdateNested */
        VendorContactUpdateNested: {
            /**
             * Vendor Contact Name
             * @description The vendor contact's name
             */
            name: string;
            /**
             * Vendor Contact Role
             * @description The vendor contact's role
             */
            role: string;
            /**
             * Vendor Contact Email
             * @description The vendor contact's email
             */
            email: string;
            /**
             * Vendor Contact Phone
             * @description The vendor contact's phone
             */
            phone: string;
            /**
             * Vendor Contact ID
             * @description The vendor contact ID
             */
            id?: number | null;
        };
        /** VendorCreate */
        VendorCreate: {
            /**
             * Active
             * @description Whether or not the vendor is active
             * @default true
             */
            active: boolean;
            /**
             * Vendor Name
             * @description The name of the vendor
             */
            name: string;
            /**
             * Vendor Contacts
             * @description The vendor's contacts
             */
            contacts: components["schemas"]["VendorContactCreateNested"][];
        };
        /** VendorRead */
        VendorRead: {
            /**
             * Active
             * @description Whether or not the vendor is active
             * @default true
             */
            active: boolean;
            /**
             * Vendor Name
             * @description The name of the vendor
             */
            name: string;
            /**
             * Vendor ID
             * @description The vendor's ID
             */
            id: number;
            /**
             * Vendor Contacts
             * @description The vendor's contacts
             */
            contacts: components["schemas"]["VendorContactRead"][];
        };
        /** VendorUpdate */
        VendorUpdate: {
            /**
             * Active
             * @description Whether or not the vendor is active
             * @default true
             */
            active: boolean;
            /**
             * Vendor Name
             * @description The name of the vendor
             */
            name: string;
            /**
             * Vendor Contacts
             * @description The vendor's contacts
             */
            contacts: components["schemas"]["VendorContactUpdateNested"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_auth_login_post"];
            };
        };
        responses: {
            /** @description The generated JWT access token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Incorrect username or password. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The provided Login is malformed or invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing, invalid, or already-expired token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_baked_good_baked_goods_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BakedGoodCreate"];
            };
        };
        responses: {
            /** @description The newly created baked good */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BakedGoodRead"];
                };
            };
            /** @description Could not validate credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient permissions. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The provided BakedGoodCreate is malformed or invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_customers_customers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The list of all customers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerRead"][];
                };
            };
        };
    };
    create_customer_customers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerCreate"];
            };
        };
        responses: {
            /** @description The newly created customer */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerRead"];
                };
            };
            /** @description Could not validate credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A customer with the given email or phone already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid values */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_customer_customers__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested customer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerRead"];
                };
            };
            /** @description The customer was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The provided path parameter is malformed or invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_customer_customers__id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerUpdate"];
            };
        };
        responses: {
            /** @description The updated customer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerRead"];
                };
            };
            /** @description Could not validate credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The customer was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A customer with the given email or phone already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The provided CustomerUpdate is malformed or invalid, or the provided path parameter is malformed or invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_customer_customers__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The customer was deleted successfully. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Could not validate credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The customer was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The provided path parameter is malformed or invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_drink_drinks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DrinkCreate"];
            };
        };
        responses: {
            /** @description The newly created drink recipe */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DrinkRead"];
                };
            };
            /** @description Could not validate credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient permissions. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The ingredient was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A drink with that name already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /**
             * @description The provided DrinkCreate is malformed or invalid. This includes:
             *     - Invalid 'type'
             *     - Invalid 'unit'
             *     - Duplicate 'ingredient_id' values
             *     - 'sale_price' is less than 'production_cost'
             *     - Attempting to convert between incompatible unit categories
             */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_employees_employees_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The list of all employees */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeRead"][];
                };
            };
        };
    };
    create_employee_employees_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeCreate"];
            };
        };
        responses: {
            /** @description The newly created employee */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeRead"];
                };
            };
            /** @description Could not validate credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient permissions. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An employee with that username already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The provided EmployeeCreate is malformed or invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_employee_employees__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested employee */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeRead"];
                };
            };
            /** @description The employee was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The provided path parameter is malformed or invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_employee_employees__id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeUpdate"];
            };
        };
        responses: {
            /** @description The updated employee */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeRead"];
                };
            };
            /** @description Could not validate credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient permissions. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The employee was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An employee with that username already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The provided EmployeeUpdate is malformed or invalid, or the provided path parameter is malformed or invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_employee_employees__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The employee was deleted successfully. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Could not validate credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient permissions. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The employee was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The provided path parameter is malformed or invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_ingredients_ingredients_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The list of ingredients */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientRead"][];
                };
            };
        };
    };
    create_ingredient_ingredients_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngredientCreate"];
            };
        };
        responses: {
            /** @description The newly created Ingredient */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientRead"];
                };
            };
            /** @description Could not validate credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient permissions. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The vendor was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An ingredient with that name and vendor ID already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The provided IngredientCreate is malformed or invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_ingredient_ingredients__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested ingredient */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientRead"];
                };
            };
            /** @description The ingredient was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The provided path parameter is malformed or invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_ingredient_ingredients__id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngredientUpdate"];
            };
        };
        responses: {
            /** @description The updated ingredient */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientRead"];
                };
            };
            /** @description Could not validate credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient permissions. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /**
             * @description The ingredient was not found.
             *
             *     The vendor was not found.
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An ingredient with that name and vendor ID already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /**
             * @description The provided path parameter is malformed or invalid.
             *
             *     The provided IngredientUpdate is malformed or invalid.
             */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_ingredient_ingredients__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The ingredient was deleted successfully. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Could not validate credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient permissions. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The ingredient was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The provided path parameter is malformed or invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_promotions_promotions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The list of Promotions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromotionRead"][];
                };
            };
        };
    };
    create_promotion_promotions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromotionCreate"];
            };
        };
        responses: {
            /** @description The newly created Promotion */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromotionRead"];
                };
            };
            /** @description Could not validate credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient permissions. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A promotion with that promo code already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The provided PromotionCreate is malformed or invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_promotion_promotions__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested Promotion */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromotionRead"];
                };
            };
            /** @description The promotion was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The provided path parameter is malformed or invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_promotion_promotions__id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromotionUpdate"];
            };
        };
        responses: {
            /** @description The updated Promotion */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromotionRead"];
                };
            };
            /** @description Could not validate credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient permissions. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The promotion was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A promotion with that promo code already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The provided PromotionUpdate is malformed or invalid, or the provided path parameter is malformed or invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_promotion_promotions__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Promotion was deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Could not validate credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient permissions. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The promotion was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The provided path parameter is malformed or invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_vendors_vendors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of all vendors */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VendorRead"][];
                };
            };
        };
    };
    create_vendor_vendors_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VendorCreate"];
            };
        };
        responses: {
            /** @description The newly created Vendor */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VendorRead"];
                };
            };
            /** @description Could not validate credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient permissions. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The provided VendorCreate is malformed or invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_vendor_vendors__id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VendorUpdate"];
            };
        };
        responses: {
            /** @description The updated vendor */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VendorRead"];
                };
            };
            /** @description Could not validate credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient permissions. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The Vendor was not found, or the VendorContact was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The provided VendorUpdate is malformed or invalid, or the provided path parameter is malformed or invalid, or the VendorContact belongs to another Vendor. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_vendor_vendors__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The vendor was deleted successfully. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Could not validate credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient permissions. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The vendor was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The vendor has associated ingredients. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The provided path parameter is malformed or invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_purchase_purchases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PurchaseCreate"];
            };
        };
        responses: {
            /** @description The newly created purchase */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurchaseRead"];
                };
            };
            /** @description Could not validate credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient permissions. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The customer was not found, or the promotion was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The provided PurchaseCreate is malformed or invalid, an unknown item name was provided, or the promotion is inactive/expired. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description The database server is not reachable. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
